name: lint

on:
  push:
    branches: [master]
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    strategy:
      matrix:
        go: [stable]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Setup
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go }}

    - name: Prepare checkout
      run: git config --global core.autocrlf false

    - name: Checkout
      uses: actions/checkout@v5

    - name: Lint
      uses: golangci/golangci-lint-action@v8.0.0
      with:
        args: --timeout=5m
